version: '3.8'

services:
  llm-server:
    build:
      context: ./llm-server
    container_name: llm_server
    ports:
      - "8000:8000"
    networks:
      - gpt2-network

  client-app:
    build:
      context: ./client-app
    container_name: client_app
    depends_on:
      - llm-server
    networks:
      - gpt2-network

networks:
  gpt2-network:
    driver: bridge
