services:
  llm-server:
    build:
      context: ./llm-server
    container_name: llm_server
    ports:
      - "8000:8000"
    networks:
      - gpt2-network
    environment:
      - FLASK_ENV=development  # Flask 개발 모드로 설정

  client-app:
    build:
      context: ./client-app
    container_name: client_app
    depends_on:
      - llm-server
    networks:
      - gpt2-network
    environment:
      - LLM_SERVER_URL=http://llm-server:8000  # 서버 URL을 환경 변수로 설정

networks:
  gpt2-network:
    driver: bridge
